// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.4
// source: agentwallet.proto

package agentwalletrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMeta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Principal      string                 `protobuf:"bytes,3,opt,name=principal,proto3" json:"principal,omitempty"`
	CapabilityId   string                 `protobuf:"bytes,4,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestMeta) Reset() {
	*x = RequestMeta{}
	mi := &file_agentwallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMeta) ProtoMessage() {}

func (x *RequestMeta) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMeta.ProtoReflect.Descriptor instead.
func (*RequestMeta) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMeta) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestMeta) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *RequestMeta) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *RequestMeta) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

type ResponseMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Warnings      []string               `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseMeta) Reset() {
	*x = ResponseMeta{}
	mi := &file_agentwallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMeta) ProtoMessage() {}

func (x *ResponseMeta) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMeta.ProtoReflect.Descriptor instead.
func (*ResponseMeta) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseMeta) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResponseMeta) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type WalletState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WalletId           string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	ActiveNetwork      uint32                 `protobuf:"varint,2,opt,name=active_network,json=activeNetwork,proto3" json:"active_network,omitempty"`
	Loaded             bool                   `protobuf:"varint,3,opt,name=loaded,proto3" json:"loaded,omitempty"`
	ChainSynced        bool                   `protobuf:"varint,4,opt,name=chain_synced,json=chainSynced,proto3" json:"chain_synced,omitempty"`
	Locked             bool                   `protobuf:"varint,5,opt,name=locked,proto3" json:"locked,omitempty"`
	CurrentBlockHeight int32                  `protobuf:"varint,6,opt,name=current_block_height,json=currentBlockHeight,proto3" json:"current_block_height,omitempty"`
	CurrentBlockHash   []byte                 `protobuf:"bytes,7,opt,name=current_block_hash,json=currentBlockHash,proto3" json:"current_block_hash,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WalletState) Reset() {
	*x = WalletState{}
	mi := &file_agentwallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletState) ProtoMessage() {}

func (x *WalletState) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletState.ProtoReflect.Descriptor instead.
func (*WalletState) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{2}
}

func (x *WalletState) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *WalletState) GetActiveNetwork() uint32 {
	if x != nil {
		return x.ActiveNetwork
	}
	return 0
}

func (x *WalletState) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *WalletState) GetChainSynced() bool {
	if x != nil {
		return x.ChainSynced
	}
	return false
}

func (x *WalletState) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *WalletState) GetCurrentBlockHeight() int32 {
	if x != nil {
		return x.CurrentBlockHeight
	}
	return 0
}

func (x *WalletState) GetCurrentBlockHash() []byte {
	if x != nil {
		return x.CurrentBlockHash
	}
	return nil
}

type GetWalletStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *RequestMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	WalletId      string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletStateRequest) Reset() {
	*x = GetWalletStateRequest{}
	mi := &file_agentwallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletStateRequest) ProtoMessage() {}

func (x *GetWalletStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletStateRequest.ProtoReflect.Descriptor instead.
func (*GetWalletStateRequest) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{3}
}

func (x *GetWalletStateRequest) GetMeta() *RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetWalletStateRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type GetWalletStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	State         *WalletState           `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletStateResponse) Reset() {
	*x = GetWalletStateResponse{}
	mi := &file_agentwallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletStateResponse) ProtoMessage() {}

func (x *GetWalletStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletStateResponse.ProtoReflect.Descriptor instead.
func (*GetWalletStateResponse) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{4}
}

func (x *GetWalletStateResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetWalletStateResponse) GetState() *WalletState {
	if x != nil {
		return x.State
	}
	return nil
}

type Utxo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Outpoint           string                 `protobuf:"bytes,1,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	AmountSat          int64                  `protobuf:"varint,2,opt,name=amount_sat,json=amountSat,proto3" json:"amount_sat,omitempty"`
	FromCoinbase       bool                   `protobuf:"varint,3,opt,name=from_coinbase,json=fromCoinbase,proto3" json:"from_coinbase,omitempty"`
	BlockHeight        int32                  `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	ReceiveTimeUnix    int64                  `protobuf:"varint,5,opt,name=receive_time_unix,json=receiveTimeUnix,proto3" json:"receive_time_unix,omitempty"`
	Address            string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Leased             bool                   `protobuf:"varint,7,opt,name=leased,proto3" json:"leased,omitempty"`
	LeaseExpiresAtUnix int64                  `protobuf:"varint,8,opt,name=lease_expires_at_unix,json=leaseExpiresAtUnix,proto3" json:"lease_expires_at_unix,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Utxo) Reset() {
	*x = Utxo{}
	mi := &file_agentwallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Utxo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Utxo) ProtoMessage() {}

func (x *Utxo) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Utxo.ProtoReflect.Descriptor instead.
func (*Utxo) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{5}
}

func (x *Utxo) GetOutpoint() string {
	if x != nil {
		return x.Outpoint
	}
	return ""
}

func (x *Utxo) GetAmountSat() int64 {
	if x != nil {
		return x.AmountSat
	}
	return 0
}

func (x *Utxo) GetFromCoinbase() bool {
	if x != nil {
		return x.FromCoinbase
	}
	return false
}

func (x *Utxo) GetBlockHeight() int32 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *Utxo) GetReceiveTimeUnix() int64 {
	if x != nil {
		return x.ReceiveTimeUnix
	}
	return 0
}

func (x *Utxo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Utxo) GetLeased() bool {
	if x != nil {
		return x.Leased
	}
	return false
}

func (x *Utxo) GetLeaseExpiresAtUnix() int64 {
	if x != nil {
		return x.LeaseExpiresAtUnix
	}
	return 0
}

type ListUtxosRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Meta             *RequestMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	WalletId         string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	AccountNumber    uint32                 `protobuf:"varint,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	MinConfirmations int32                  `protobuf:"varint,4,opt,name=min_confirmations,json=minConfirmations,proto3" json:"min_confirmations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListUtxosRequest) Reset() {
	*x = ListUtxosRequest{}
	mi := &file_agentwallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUtxosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUtxosRequest) ProtoMessage() {}

func (x *ListUtxosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUtxosRequest.ProtoReflect.Descriptor instead.
func (*ListUtxosRequest) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{6}
}

func (x *ListUtxosRequest) GetMeta() *RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ListUtxosRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *ListUtxosRequest) GetAccountNumber() uint32 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *ListUtxosRequest) GetMinConfirmations() int32 {
	if x != nil {
		return x.MinConfirmations
	}
	return 0
}

type ListUtxosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Utxos         []*Utxo                `protobuf:"bytes,2,rep,name=utxos,proto3" json:"utxos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUtxosResponse) Reset() {
	*x = ListUtxosResponse{}
	mi := &file_agentwallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUtxosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUtxosResponse) ProtoMessage() {}

func (x *ListUtxosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUtxosResponse.ProtoReflect.Descriptor instead.
func (*ListUtxosResponse) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{7}
}

func (x *ListUtxosResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ListUtxosResponse) GetUtxos() []*Utxo {
	if x != nil {
		return x.Utxos
	}
	return nil
}

type ExpiryPolicy struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	WindowBlocks             uint64                 `protobuf:"varint,1,opt,name=window_blocks,json=windowBlocks,proto3" json:"window_blocks,omitempty"`
	ExpiringThresholdBlocks  int32                  `protobuf:"varint,2,opt,name=expiring_threshold_blocks,json=expiringThresholdBlocks,proto3" json:"expiring_threshold_blocks,omitempty"`
	DustThresholdSat         int64                  `protobuf:"varint,3,opt,name=dust_threshold_sat,json=dustThresholdSat,proto3" json:"dust_threshold_sat,omitempty"`
	ProjectedReclaimRatioBps uint32                 `protobuf:"varint,4,opt,name=projected_reclaim_ratio_bps,json=projectedReclaimRatioBps,proto3" json:"projected_reclaim_ratio_bps,omitempty"`
	Source                   string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ExpiryPolicy) Reset() {
	*x = ExpiryPolicy{}
	mi := &file_agentwallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpiryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpiryPolicy) ProtoMessage() {}

func (x *ExpiryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpiryPolicy.ProtoReflect.Descriptor instead.
func (*ExpiryPolicy) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{8}
}

func (x *ExpiryPolicy) GetWindowBlocks() uint64 {
	if x != nil {
		return x.WindowBlocks
	}
	return 0
}

func (x *ExpiryPolicy) GetExpiringThresholdBlocks() int32 {
	if x != nil {
		return x.ExpiringThresholdBlocks
	}
	return 0
}

func (x *ExpiryPolicy) GetDustThresholdSat() int64 {
	if x != nil {
		return x.DustThresholdSat
	}
	return 0
}

func (x *ExpiryPolicy) GetProjectedReclaimRatioBps() uint32 {
	if x != nil {
		return x.ProjectedReclaimRatioBps
	}
	return 0
}

func (x *ExpiryPolicy) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ExpiryRisk struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Outpoint       string                 `protobuf:"bytes,1,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	AmountSat      int64                  `protobuf:"varint,2,opt,name=amount_sat,json=amountSat,proto3" json:"amount_sat,omitempty"`
	CreateHeight   int32                  `protobuf:"varint,3,opt,name=create_height,json=createHeight,proto3" json:"create_height,omitempty"`
	ExpiryHeight   int32                  `protobuf:"varint,4,opt,name=expiry_height,json=expiryHeight,proto3" json:"expiry_height,omitempty"`
	BlocksToExpiry int32                  `protobuf:"varint,5,opt,name=blocks_to_expiry,json=blocksToExpiry,proto3" json:"blocks_to_expiry,omitempty"`
	DaysToExpiry   int32                  `protobuf:"varint,6,opt,name=days_to_expiry,json=daysToExpiry,proto3" json:"days_to_expiry,omitempty"`
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	DustRisk       bool                   `protobuf:"varint,8,opt,name=dust_risk,json=dustRisk,proto3" json:"dust_risk,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExpiryRisk) Reset() {
	*x = ExpiryRisk{}
	mi := &file_agentwallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpiryRisk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpiryRisk) ProtoMessage() {}

func (x *ExpiryRisk) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpiryRisk.ProtoReflect.Descriptor instead.
func (*ExpiryRisk) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{9}
}

func (x *ExpiryRisk) GetOutpoint() string {
	if x != nil {
		return x.Outpoint
	}
	return ""
}

func (x *ExpiryRisk) GetAmountSat() int64 {
	if x != nil {
		return x.AmountSat
	}
	return 0
}

func (x *ExpiryRisk) GetCreateHeight() int32 {
	if x != nil {
		return x.CreateHeight
	}
	return 0
}

func (x *ExpiryRisk) GetExpiryHeight() int32 {
	if x != nil {
		return x.ExpiryHeight
	}
	return 0
}

func (x *ExpiryRisk) GetBlocksToExpiry() int32 {
	if x != nil {
		return x.BlocksToExpiry
	}
	return 0
}

func (x *ExpiryRisk) GetDaysToExpiry() int32 {
	if x != nil {
		return x.DaysToExpiry
	}
	return 0
}

func (x *ExpiryRisk) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExpiryRisk) GetDustRisk() bool {
	if x != nil {
		return x.DustRisk
	}
	return false
}

type GetExpiryRiskRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Meta             *RequestMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	WalletId         string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	AccountNumber    uint32                 `protobuf:"varint,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Outpoints        []string               `protobuf:"bytes,4,rep,name=outpoints,proto3" json:"outpoints,omitempty"`
	MinConfirmations int32                  `protobuf:"varint,5,opt,name=min_confirmations,json=minConfirmations,proto3" json:"min_confirmations,omitempty"`
	Limit            uint32                 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	BeforeHeight     int32                  `protobuf:"varint,7,opt,name=before_height,json=beforeHeight,proto3" json:"before_height,omitempty"`
	Policy           *ExpiryPolicy          `protobuf:"bytes,8,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetExpiryRiskRequest) Reset() {
	*x = GetExpiryRiskRequest{}
	mi := &file_agentwallet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpiryRiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpiryRiskRequest) ProtoMessage() {}

func (x *GetExpiryRiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpiryRiskRequest.ProtoReflect.Descriptor instead.
func (*GetExpiryRiskRequest) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{10}
}

func (x *GetExpiryRiskRequest) GetMeta() *RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetExpiryRiskRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *GetExpiryRiskRequest) GetAccountNumber() uint32 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *GetExpiryRiskRequest) GetOutpoints() []string {
	if x != nil {
		return x.Outpoints
	}
	return nil
}

func (x *GetExpiryRiskRequest) GetMinConfirmations() int32 {
	if x != nil {
		return x.MinConfirmations
	}
	return 0
}

func (x *GetExpiryRiskRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetExpiryRiskRequest) GetBeforeHeight() int32 {
	if x != nil {
		return x.BeforeHeight
	}
	return 0
}

func (x *GetExpiryRiskRequest) GetPolicy() *ExpiryPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type GetExpiryRiskResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Meta            *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	TipHeight       int32                  `protobuf:"varint,2,opt,name=tip_height,json=tipHeight,proto3" json:"tip_height,omitempty"`
	EffectivePolicy *ExpiryPolicy          `protobuf:"bytes,3,opt,name=effective_policy,json=effectivePolicy,proto3" json:"effective_policy,omitempty"`
	Items           []*ExpiryRisk          `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetExpiryRiskResponse) Reset() {
	*x = GetExpiryRiskResponse{}
	mi := &file_agentwallet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpiryRiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpiryRiskResponse) ProtoMessage() {}

func (x *GetExpiryRiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpiryRiskResponse.ProtoReflect.Descriptor instead.
func (*GetExpiryRiskResponse) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{11}
}

func (x *GetExpiryRiskResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetExpiryRiskResponse) GetTipHeight() int32 {
	if x != nil {
		return x.TipHeight
	}
	return 0
}

func (x *GetExpiryRiskResponse) GetEffectivePolicy() *ExpiryPolicy {
	if x != nil {
		return x.EffectivePolicy
	}
	return nil
}

func (x *GetExpiryRiskResponse) GetItems() []*ExpiryRisk {
	if x != nil {
		return x.Items
	}
	return nil
}

type TransactionSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InputCount        int32                  `protobuf:"varint,1,opt,name=input_count,json=inputCount,proto3" json:"input_count,omitempty"`
	OutputCount       int32                  `protobuf:"varint,2,opt,name=output_count,json=outputCount,proto3" json:"output_count,omitempty"`
	TotalInputSat     int64                  `protobuf:"varint,3,opt,name=total_input_sat,json=totalInputSat,proto3" json:"total_input_sat,omitempty"`
	TotalOutputSat    int64                  `protobuf:"varint,4,opt,name=total_output_sat,json=totalOutputSat,proto3" json:"total_output_sat,omitempty"`
	EstimatedFeeSat   int64                  `protobuf:"varint,5,opt,name=estimated_fee_sat,json=estimatedFeeSat,proto3" json:"estimated_fee_sat,omitempty"`
	ChangeOutputIndex int32                  `protobuf:"varint,6,opt,name=change_output_index,json=changeOutputIndex,proto3" json:"change_output_index,omitempty"`
	TargetOutputIndex int32                  `protobuf:"varint,7,opt,name=target_output_index,json=targetOutputIndex,proto3" json:"target_output_index,omitempty"`
	TargetAddress     string                 `protobuf:"bytes,8,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	TargetAmountSat   int64                  `protobuf:"varint,9,opt,name=target_amount_sat,json=targetAmountSat,proto3" json:"target_amount_sat,omitempty"`
	FeeRateSatPerKb   int64                  `protobuf:"varint,10,opt,name=fee_rate_sat_per_kb,json=feeRateSatPerKb,proto3" json:"fee_rate_sat_per_kb,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransactionSummary) Reset() {
	*x = TransactionSummary{}
	mi := &file_agentwallet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionSummary) ProtoMessage() {}

func (x *TransactionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionSummary.ProtoReflect.Descriptor instead.
func (*TransactionSummary) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{12}
}

func (x *TransactionSummary) GetInputCount() int32 {
	if x != nil {
		return x.InputCount
	}
	return 0
}

func (x *TransactionSummary) GetOutputCount() int32 {
	if x != nil {
		return x.OutputCount
	}
	return 0
}

func (x *TransactionSummary) GetTotalInputSat() int64 {
	if x != nil {
		return x.TotalInputSat
	}
	return 0
}

func (x *TransactionSummary) GetTotalOutputSat() int64 {
	if x != nil {
		return x.TotalOutputSat
	}
	return 0
}

func (x *TransactionSummary) GetEstimatedFeeSat() int64 {
	if x != nil {
		return x.EstimatedFeeSat
	}
	return 0
}

func (x *TransactionSummary) GetChangeOutputIndex() int32 {
	if x != nil {
		return x.ChangeOutputIndex
	}
	return 0
}

func (x *TransactionSummary) GetTargetOutputIndex() int32 {
	if x != nil {
		return x.TargetOutputIndex
	}
	return 0
}

func (x *TransactionSummary) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *TransactionSummary) GetTargetAmountSat() int64 {
	if x != nil {
		return x.TargetAmountSat
	}
	return 0
}

func (x *TransactionSummary) GetFeeRateSatPerKb() int64 {
	if x != nil {
		return x.FeeRateSatPerKb
	}
	return 0
}

type Operation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationId      string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Kind             string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	State            string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	WalletId         string                 `protobuf:"bytes,4,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	AccountNumber    uint32                 `protobuf:"varint,5,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Outpoints        []string               `protobuf:"bytes,6,rep,name=outpoints,proto3" json:"outpoints,omitempty"`
	PolicyVerdict    string                 `protobuf:"bytes,7,opt,name=policy_verdict,json=policyVerdict,proto3" json:"policy_verdict,omitempty"`
	Warnings         []string               `protobuf:"bytes,8,rep,name=warnings,proto3" json:"warnings,omitempty"`
	CreatedAtUnix    int64                  `protobuf:"varint,9,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix    int64                  `protobuf:"varint,10,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	ReservationId    string                 `protobuf:"bytes,11,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Summary          *TransactionSummary    `protobuf:"bytes,12,opt,name=summary,proto3" json:"summary,omitempty"`
	ExpiryRisks      []*ExpiryRisk          `protobuf:"bytes,13,rep,name=expiry_risks,json=expiryRisks,proto3" json:"expiry_risks,omitempty"`
	EffectivePolicy  *ExpiryPolicy          `protobuf:"bytes,14,opt,name=effective_policy,json=effectivePolicy,proto3" json:"effective_policy,omitempty"`
	MinConfirmations int32                  `protobuf:"varint,15,opt,name=min_confirmations,json=minConfirmations,proto3" json:"min_confirmations,omitempty"`
	Txid             string                 `protobuf:"bytes,16,opt,name=txid,proto3" json:"txid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_agentwallet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{13}
}

func (x *Operation) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *Operation) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Operation) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Operation) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *Operation) GetAccountNumber() uint32 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *Operation) GetOutpoints() []string {
	if x != nil {
		return x.Outpoints
	}
	return nil
}

func (x *Operation) GetPolicyVerdict() string {
	if x != nil {
		return x.PolicyVerdict
	}
	return ""
}

func (x *Operation) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *Operation) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *Operation) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *Operation) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *Operation) GetSummary() *TransactionSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *Operation) GetExpiryRisks() []*ExpiryRisk {
	if x != nil {
		return x.ExpiryRisks
	}
	return nil
}

func (x *Operation) GetEffectivePolicy() *ExpiryPolicy {
	if x != nil {
		return x.EffectivePolicy
	}
	return nil
}

func (x *Operation) GetMinConfirmations() int32 {
	if x != nil {
		return x.MinConfirmations
	}
	return 0
}

func (x *Operation) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

type PreviewRenewalRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Meta               *RequestMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	WalletId           string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	AccountNumber      uint32                 `protobuf:"varint,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Outpoints          []string               `protobuf:"bytes,4,rep,name=outpoints,proto3" json:"outpoints,omitempty"`
	DryRun             bool                   `protobuf:"varint,5,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	MaxFeeRateSatPerKb int64                  `protobuf:"varint,6,opt,name=max_fee_rate_sat_per_kb,json=maxFeeRateSatPerKb,proto3" json:"max_fee_rate_sat_per_kb,omitempty"`
	TargetAmountSat    int64                  `protobuf:"varint,7,opt,name=target_amount_sat,json=targetAmountSat,proto3" json:"target_amount_sat,omitempty"`
	TargetAddress      string                 `protobuf:"bytes,8,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	MinConfirmations   int32                  `protobuf:"varint,9,opt,name=min_confirmations,json=minConfirmations,proto3" json:"min_confirmations,omitempty"`
	ReservationId      string                 `protobuf:"bytes,10,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	ExpiryPolicy       *ExpiryPolicy          `protobuf:"bytes,11,opt,name=expiry_policy,json=expiryPolicy,proto3" json:"expiry_policy,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PreviewRenewalRequest) Reset() {
	*x = PreviewRenewalRequest{}
	mi := &file_agentwallet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewRenewalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewRenewalRequest) ProtoMessage() {}

func (x *PreviewRenewalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewRenewalRequest.ProtoReflect.Descriptor instead.
func (*PreviewRenewalRequest) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{14}
}

func (x *PreviewRenewalRequest) GetMeta() *RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PreviewRenewalRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *PreviewRenewalRequest) GetAccountNumber() uint32 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *PreviewRenewalRequest) GetOutpoints() []string {
	if x != nil {
		return x.Outpoints
	}
	return nil
}

func (x *PreviewRenewalRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *PreviewRenewalRequest) GetMaxFeeRateSatPerKb() int64 {
	if x != nil {
		return x.MaxFeeRateSatPerKb
	}
	return 0
}

func (x *PreviewRenewalRequest) GetTargetAmountSat() int64 {
	if x != nil {
		return x.TargetAmountSat
	}
	return 0
}

func (x *PreviewRenewalRequest) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *PreviewRenewalRequest) GetMinConfirmations() int32 {
	if x != nil {
		return x.MinConfirmations
	}
	return 0
}

func (x *PreviewRenewalRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *PreviewRenewalRequest) GetExpiryPolicy() *ExpiryPolicy {
	if x != nil {
		return x.ExpiryPolicy
	}
	return nil
}

type PreviewRenewalResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Meta            *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Operation       *Operation             `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	UnsignedPsbt    []byte                 `protobuf:"bytes,3,opt,name=unsigned_psbt,json=unsignedPsbt,proto3" json:"unsigned_psbt,omitempty"`
	UnsignedPsbtB64 string                 `protobuf:"bytes,4,opt,name=unsigned_psbt_b64,json=unsignedPsbtB64,proto3" json:"unsigned_psbt_b64,omitempty"`
	Summary         *TransactionSummary    `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	EffectivePolicy *ExpiryPolicy          `protobuf:"bytes,6,opt,name=effective_policy,json=effectivePolicy,proto3" json:"effective_policy,omitempty"`
	ExpiryRisks     []*ExpiryRisk          `protobuf:"bytes,7,rep,name=expiry_risks,json=expiryRisks,proto3" json:"expiry_risks,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PreviewRenewalResponse) Reset() {
	*x = PreviewRenewalResponse{}
	mi := &file_agentwallet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewRenewalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewRenewalResponse) ProtoMessage() {}

func (x *PreviewRenewalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewRenewalResponse.ProtoReflect.Descriptor instead.
func (*PreviewRenewalResponse) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{15}
}

func (x *PreviewRenewalResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *PreviewRenewalResponse) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *PreviewRenewalResponse) GetUnsignedPsbt() []byte {
	if x != nil {
		return x.UnsignedPsbt
	}
	return nil
}

func (x *PreviewRenewalResponse) GetUnsignedPsbtB64() string {
	if x != nil {
		return x.UnsignedPsbtB64
	}
	return ""
}

func (x *PreviewRenewalResponse) GetSummary() *TransactionSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *PreviewRenewalResponse) GetEffectivePolicy() *ExpiryPolicy {
	if x != nil {
		return x.EffectivePolicy
	}
	return nil
}

func (x *PreviewRenewalResponse) GetExpiryRisks() []*ExpiryRisk {
	if x != nil {
		return x.ExpiryRisks
	}
	return nil
}

type SubmitRenewalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *RequestMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRenewalRequest) Reset() {
	*x = SubmitRenewalRequest{}
	mi := &file_agentwallet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRenewalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRenewalRequest) ProtoMessage() {}

func (x *SubmitRenewalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRenewalRequest.ProtoReflect.Descriptor instead.
func (*SubmitRenewalRequest) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{16}
}

func (x *SubmitRenewalRequest) GetMeta() *RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SubmitRenewalRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *SubmitRenewalRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type SubmitRenewalResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Meta            *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Operation       *Operation             `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Txid            string                 `protobuf:"bytes,3,opt,name=txid,proto3" json:"txid,omitempty"`
	RawTransaction  []byte                 `protobuf:"bytes,4,opt,name=raw_transaction,json=rawTransaction,proto3" json:"raw_transaction,omitempty"`
	Summary         *TransactionSummary    `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	EffectivePolicy *ExpiryPolicy          `protobuf:"bytes,6,opt,name=effective_policy,json=effectivePolicy,proto3" json:"effective_policy,omitempty"`
	ExpiryRisks     []*ExpiryRisk          `protobuf:"bytes,7,rep,name=expiry_risks,json=expiryRisks,proto3" json:"expiry_risks,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitRenewalResponse) Reset() {
	*x = SubmitRenewalResponse{}
	mi := &file_agentwallet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRenewalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRenewalResponse) ProtoMessage() {}

func (x *SubmitRenewalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRenewalResponse.ProtoReflect.Descriptor instead.
func (*SubmitRenewalResponse) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{17}
}

func (x *SubmitRenewalResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *SubmitRenewalResponse) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *SubmitRenewalResponse) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *SubmitRenewalResponse) GetRawTransaction() []byte {
	if x != nil {
		return x.RawTransaction
	}
	return nil
}

func (x *SubmitRenewalResponse) GetSummary() *TransactionSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *SubmitRenewalResponse) GetEffectivePolicy() *ExpiryPolicy {
	if x != nil {
		return x.EffectivePolicy
	}
	return nil
}

func (x *SubmitRenewalResponse) GetExpiryRisks() []*ExpiryRisk {
	if x != nil {
		return x.ExpiryRisks
	}
	return nil
}

type ReserveUtxosRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Meta             *RequestMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	WalletId         string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	AccountNumber    uint32                 `protobuf:"varint,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Outpoints        []string               `protobuf:"bytes,4,rep,name=outpoints,proto3" json:"outpoints,omitempty"`
	TtlSeconds       int64                  `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	MinConfirmations int32                  `protobuf:"varint,6,opt,name=min_confirmations,json=minConfirmations,proto3" json:"min_confirmations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReserveUtxosRequest) Reset() {
	*x = ReserveUtxosRequest{}
	mi := &file_agentwallet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveUtxosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveUtxosRequest) ProtoMessage() {}

func (x *ReserveUtxosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveUtxosRequest.ProtoReflect.Descriptor instead.
func (*ReserveUtxosRequest) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{18}
}

func (x *ReserveUtxosRequest) GetMeta() *RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ReserveUtxosRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *ReserveUtxosRequest) GetAccountNumber() uint32 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *ReserveUtxosRequest) GetOutpoints() []string {
	if x != nil {
		return x.Outpoints
	}
	return nil
}

func (x *ReserveUtxosRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *ReserveUtxosRequest) GetMinConfirmations() int32 {
	if x != nil {
		return x.MinConfirmations
	}
	return 0
}

type ReserveUtxosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	ExpiresAtUnix int64                  `protobuf:"varint,3,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	Outpoints     []string               `protobuf:"bytes,4,rep,name=outpoints,proto3" json:"outpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveUtxosResponse) Reset() {
	*x = ReserveUtxosResponse{}
	mi := &file_agentwallet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveUtxosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveUtxosResponse) ProtoMessage() {}

func (x *ReserveUtxosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveUtxosResponse.ProtoReflect.Descriptor instead.
func (*ReserveUtxosResponse) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{19}
}

func (x *ReserveUtxosResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ReserveUtxosResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveUtxosResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *ReserveUtxosResponse) GetOutpoints() []string {
	if x != nil {
		return x.Outpoints
	}
	return nil
}

type ReleaseReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *RequestMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservationRequest) Reset() {
	*x = ReleaseReservationRequest{}
	mi := &file_agentwallet_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationRequest) ProtoMessage() {}

func (x *ReleaseReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationRequest.ProtoReflect.Descriptor instead.
func (*ReleaseReservationRequest) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{20}
}

func (x *ReleaseReservationRequest) GetMeta() *RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ReleaseReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type ReleaseReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Released      bool                   `protobuf:"varint,3,opt,name=released,proto3" json:"released,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservationResponse) Reset() {
	*x = ReleaseReservationResponse{}
	mi := &file_agentwallet_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationResponse) ProtoMessage() {}

func (x *ReleaseReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationResponse.ProtoReflect.Descriptor instead.
func (*ReleaseReservationResponse) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{21}
}

func (x *ReleaseReservationResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ReleaseReservationResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReleaseReservationResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *RequestMeta           `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_agentwallet_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{22}
}

func (x *GetOperationRequest) GetMeta() *RequestMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ResponseMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Operation     *Operation             `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationResponse) Reset() {
	*x = GetOperationResponse{}
	mi := &file_agentwallet_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationResponse) ProtoMessage() {}

func (x *GetOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentwallet_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationResponse.ProtoReflect.Descriptor instead.
func (*GetOperationResponse) Descriptor() ([]byte, []int) {
	return file_agentwallet_proto_rawDescGZIP(), []int{23}
}

func (x *GetOperationResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetOperationResponse) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

var File_agentwallet_proto protoreflect.FileDescriptor

const file_agentwallet_proto_rawDesc = "" +
	"\n" +
	"\x11agentwallet.proto\x12\x0eagentwalletrpc\"\x98\x01\n" +
	"\vRequestMeta\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x1c\n" +
	"\tprincipal\x18\x03 \x01(\tR\tprincipal\x12#\n" +
	"\rcapability_id\x18\x04 \x01(\tR\fcapabilityId\"I\n" +
	"\fResponseMeta\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bwarnings\x18\x02 \x03(\tR\bwarnings\"\x84\x02\n" +
	"\vWalletState\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12%\n" +
	"\x0eactive_network\x18\x02 \x01(\rR\ractiveNetwork\x12\x16\n" +
	"\x06loaded\x18\x03 \x01(\bR\x06loaded\x12!\n" +
	"\fchain_synced\x18\x04 \x01(\bR\vchainSynced\x12\x16\n" +
	"\x06locked\x18\x05 \x01(\bR\x06locked\x120\n" +
	"\x14current_block_height\x18\x06 \x01(\x05R\x12currentBlockHeight\x12,\n" +
	"\x12current_block_hash\x18\a \x01(\fR\x10currentBlockHash\"e\n" +
	"\x15GetWalletStateRequest\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.agentwalletrpc.RequestMetaR\x04meta\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\"}\n" +
	"\x16GetWalletStateResponse\x120\n" +
	"\x04meta\x18\x01 \x01(\v2\x1c.agentwalletrpc.ResponseMetaR\x04meta\x121\n" +
	"\x05state\x18\x02 \x01(\v2\x1b.agentwalletrpc.WalletStateR\x05state\"\x9a\x02\n" +
	"\x04Utxo\x12\x1a\n" +
	"\boutpoint\x18\x01 \x01(\tR\boutpoint\x12\x1d\n" +
	"\n" +
	"amount_sat\x18\x02 \x01(\x03R\tamountSat\x12#\n" +
	"\rfrom_coinbase\x18\x03 \x01(\bR\ffromCoinbase\x12!\n" +
	"\fblock_height\x18\x04 \x01(\x05R\vblockHeight\x12*\n" +
	"\x11receive_time_unix\x18\x05 \x01(\x03R\x0freceiveTimeUnix\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12\x16\n" +
	"\x06leased\x18\a \x01(\bR\x06leased\x121\n" +
	"\x15lease_expires_at_unix\x18\b \x01(\x03R\x12leaseExpiresAtUnix\"\xb4\x01\n" +
	"\x10ListUtxosRequest\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.agentwalletrpc.RequestMetaR\x04meta\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\rR\raccountNumber\x12+\n" +
	"\x11min_confirmations\x18\x04 \x01(\x05R\x10minConfirmations\"q\n" +
	"\x11ListUtxosResponse\x120\n" +
	"\x04meta\x18\x01 \x01(\v2\x1c.agentwalletrpc.ResponseMetaR\x04meta\x12*\n" +
	"\x05utxos\x18\x02 \x03(\v2\x14.agentwalletrpc.UtxoR\x05utxos\"\xf4\x01\n" +
	"\fExpiryPolicy\x12#\n" +
	"\rwindow_blocks\x18\x01 \x01(\x04R\fwindowBlocks\x12:\n" +
	"\x19expiring_threshold_blocks\x18\x02 \x01(\x05R\x17expiringThresholdBlocks\x12,\n" +
	"\x12dust_threshold_sat\x18\x03 \x01(\x03R\x10dustThresholdSat\x12=\n" +
	"\x1bprojected_reclaim_ratio_bps\x18\x04 \x01(\rR\x18projectedReclaimRatioBps\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"\x96\x02\n" +
	"\n" +
	"ExpiryRisk\x12\x1a\n" +
	"\boutpoint\x18\x01 \x01(\tR\boutpoint\x12\x1d\n" +
	"\n" +
	"amount_sat\x18\x02 \x01(\x03R\tamountSat\x12#\n" +
	"\rcreate_height\x18\x03 \x01(\x05R\fcreateHeight\x12#\n" +
	"\rexpiry_height\x18\x04 \x01(\x05R\fexpiryHeight\x12(\n" +
	"\x10blocks_to_expiry\x18\x05 \x01(\x05R\x0eblocksToExpiry\x12$\n" +
	"\x0edays_to_expiry\x18\x06 \x01(\x05R\fdaysToExpiry\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1b\n" +
	"\tdust_risk\x18\b \x01(\bR\bdustRisk\"\xc7\x02\n" +
	"\x14GetExpiryRiskRequest\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.agentwalletrpc.RequestMetaR\x04meta\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\rR\raccountNumber\x12\x1c\n" +
	"\toutpoints\x18\x04 \x03(\tR\toutpoints\x12+\n" +
	"\x11min_confirmations\x18\x05 \x01(\x05R\x10minConfirmations\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\rR\x05limit\x12#\n" +
	"\rbefore_height\x18\a \x01(\x05R\fbeforeHeight\x124\n" +
	"\x06policy\x18\b \x01(\v2\x1c.agentwalletrpc.ExpiryPolicyR\x06policy\"\xe3\x01\n" +
	"\x15GetExpiryRiskResponse\x120\n" +
	"\x04meta\x18\x01 \x01(\v2\x1c.agentwalletrpc.ResponseMetaR\x04meta\x12\x1d\n" +
	"\n" +
	"tip_height\x18\x02 \x01(\x05R\ttipHeight\x12G\n" +
	"\x10effective_policy\x18\x03 \x01(\v2\x1c.agentwalletrpc.ExpiryPolicyR\x0feffectivePolicy\x120\n" +
	"\x05items\x18\x04 \x03(\v2\x1a.agentwalletrpc.ExpiryRiskR\x05items\"\xb7\x03\n" +
	"\x12TransactionSummary\x12\x1f\n" +
	"\vinput_count\x18\x01 \x01(\x05R\n" +
	"inputCount\x12!\n" +
	"\foutput_count\x18\x02 \x01(\x05R\voutputCount\x12&\n" +
	"\x0ftotal_input_sat\x18\x03 \x01(\x03R\rtotalInputSat\x12(\n" +
	"\x10total_output_sat\x18\x04 \x01(\x03R\x0etotalOutputSat\x12*\n" +
	"\x11estimated_fee_sat\x18\x05 \x01(\x03R\x0festimatedFeeSat\x12.\n" +
	"\x13change_output_index\x18\x06 \x01(\x05R\x11changeOutputIndex\x12.\n" +
	"\x13target_output_index\x18\a \x01(\x05R\x11targetOutputIndex\x12%\n" +
	"\x0etarget_address\x18\b \x01(\tR\rtargetAddress\x12*\n" +
	"\x11target_amount_sat\x18\t \x01(\x03R\x0ftargetAmountSat\x12,\n" +
	"\x13fee_rate_sat_per_kb\x18\n" +
	" \x01(\x03R\x0ffeeRateSatPerKb\"\xfb\x04\n" +
	"\tOperation\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1b\n" +
	"\twallet_id\x18\x04 \x01(\tR\bwalletId\x12%\n" +
	"\x0eaccount_number\x18\x05 \x01(\rR\raccountNumber\x12\x1c\n" +
	"\toutpoints\x18\x06 \x03(\tR\toutpoints\x12%\n" +
	"\x0epolicy_verdict\x18\a \x01(\tR\rpolicyVerdict\x12\x1a\n" +
	"\bwarnings\x18\b \x03(\tR\bwarnings\x12&\n" +
	"\x0fcreated_at_unix\x18\t \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\n" +
	" \x01(\x03R\rupdatedAtUnix\x12%\n" +
	"\x0ereservation_id\x18\v \x01(\tR\rreservationId\x12<\n" +
	"\asummary\x18\f \x01(\v2\".agentwalletrpc.TransactionSummaryR\asummary\x12=\n" +
	"\fexpiry_risks\x18\r \x03(\v2\x1a.agentwalletrpc.ExpiryRiskR\vexpiryRisks\x12G\n" +
	"\x10effective_policy\x18\x0e \x01(\v2\x1c.agentwalletrpc.ExpiryPolicyR\x0feffectivePolicy\x12+\n" +
	"\x11min_confirmations\x18\x0f \x01(\x05R\x10minConfirmations\x12\x12\n" +
	"\x04txid\x18\x10 \x01(\tR\x04txid\"\xe2\x03\n" +
	"\x15PreviewRenewalRequest\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.agentwalletrpc.RequestMetaR\x04meta\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\rR\raccountNumber\x12\x1c\n" +
	"\toutpoints\x18\x04 \x03(\tR\toutpoints\x12\x17\n" +
	"\adry_run\x18\x05 \x01(\bR\x06dryRun\x123\n" +
	"\x17max_fee_rate_sat_per_kb\x18\x06 \x01(\x03R\x12maxFeeRateSatPerKb\x12*\n" +
	"\x11target_amount_sat\x18\a \x01(\x03R\x0ftargetAmountSat\x12%\n" +
	"\x0etarget_address\x18\b \x01(\tR\rtargetAddress\x12+\n" +
	"\x11min_confirmations\x18\t \x01(\x05R\x10minConfirmations\x12%\n" +
	"\x0ereservation_id\x18\n" +
	" \x01(\tR\rreservationId\x12A\n" +
	"\rexpiry_policy\x18\v \x01(\v2\x1c.agentwalletrpc.ExpiryPolicyR\fexpiryPolicy\"\x9a\x03\n" +
	"\x16PreviewRenewalResponse\x120\n" +
	"\x04meta\x18\x01 \x01(\v2\x1c.agentwalletrpc.ResponseMetaR\x04meta\x127\n" +
	"\toperation\x18\x02 \x01(\v2\x19.agentwalletrpc.OperationR\toperation\x12#\n" +
	"\runsigned_psbt\x18\x03 \x01(\fR\funsignedPsbt\x12*\n" +
	"\x11unsigned_psbt_b64\x18\x04 \x01(\tR\x0funsignedPsbtB64\x12<\n" +
	"\asummary\x18\x05 \x01(\v2\".agentwalletrpc.TransactionSummaryR\asummary\x12G\n" +
	"\x10effective_policy\x18\x06 \x01(\v2\x1c.agentwalletrpc.ExpiryPolicyR\x0feffectivePolicy\x12=\n" +
	"\fexpiry_risks\x18\a \x03(\v2\x1a.agentwalletrpc.ExpiryRiskR\vexpiryRisks\"\x80\x01\n" +
	"\x14SubmitRenewalRequest\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.agentwalletrpc.RequestMetaR\x04meta\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"\x85\x03\n" +
	"\x15SubmitRenewalResponse\x120\n" +
	"\x04meta\x18\x01 \x01(\v2\x1c.agentwalletrpc.ResponseMetaR\x04meta\x127\n" +
	"\toperation\x18\x02 \x01(\v2\x19.agentwalletrpc.OperationR\toperation\x12\x12\n" +
	"\x04txid\x18\x03 \x01(\tR\x04txid\x12'\n" +
	"\x0fraw_transaction\x18\x04 \x01(\fR\x0erawTransaction\x12<\n" +
	"\asummary\x18\x05 \x01(\v2\".agentwalletrpc.TransactionSummaryR\asummary\x12G\n" +
	"\x10effective_policy\x18\x06 \x01(\v2\x1c.agentwalletrpc.ExpiryPolicyR\x0feffectivePolicy\x12=\n" +
	"\fexpiry_risks\x18\a \x03(\v2\x1a.agentwalletrpc.ExpiryRiskR\vexpiryRisks\"\xf6\x01\n" +
	"\x13ReserveUtxosRequest\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.agentwalletrpc.RequestMetaR\x04meta\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\rR\raccountNumber\x12\x1c\n" +
	"\toutpoints\x18\x04 \x03(\tR\toutpoints\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\x03R\n" +
	"ttlSeconds\x12+\n" +
	"\x11min_confirmations\x18\x06 \x01(\x05R\x10minConfirmations\"\xb5\x01\n" +
	"\x14ReserveUtxosResponse\x120\n" +
	"\x04meta\x18\x01 \x01(\v2\x1c.agentwalletrpc.ResponseMetaR\x04meta\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12&\n" +
	"\x0fexpires_at_unix\x18\x03 \x01(\x03R\rexpiresAtUnix\x12\x1c\n" +
	"\toutpoints\x18\x04 \x03(\tR\toutpoints\"s\n" +
	"\x19ReleaseReservationRequest\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.agentwalletrpc.RequestMetaR\x04meta\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\"\x91\x01\n" +
	"\x1aReleaseReservationResponse\x120\n" +
	"\x04meta\x18\x01 \x01(\v2\x1c.agentwalletrpc.ResponseMetaR\x04meta\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12\x1a\n" +
	"\breleased\x18\x03 \x01(\bR\breleased\"i\n" +
	"\x13GetOperationRequest\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.agentwalletrpc.RequestMetaR\x04meta\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\"\x81\x01\n" +
	"\x14GetOperationResponse\x120\n" +
	"\x04meta\x18\x01 \x01(\v2\x1c.agentwalletrpc.ResponseMetaR\x04meta\x127\n" +
	"\toperation\x18\x02 \x01(\v2\x19.agentwalletrpc.OperationR\toperation2\x87\x06\n" +
	"\x12AgentWalletService\x12_\n" +
	"\x0eGetWalletState\x12%.agentwalletrpc.GetWalletStateRequest\x1a&.agentwalletrpc.GetWalletStateResponse\x12P\n" +
	"\tListUtxos\x12 .agentwalletrpc.ListUtxosRequest\x1a!.agentwalletrpc.ListUtxosResponse\x12\\\n" +
	"\rGetExpiryRisk\x12$.agentwalletrpc.GetExpiryRiskRequest\x1a%.agentwalletrpc.GetExpiryRiskResponse\x12_\n" +
	"\x0ePreviewRenewal\x12%.agentwalletrpc.PreviewRenewalRequest\x1a&.agentwalletrpc.PreviewRenewalResponse\x12\\\n" +
	"\rSubmitRenewal\x12$.agentwalletrpc.SubmitRenewalRequest\x1a%.agentwalletrpc.SubmitRenewalResponse\x12Y\n" +
	"\fReserveUtxos\x12#.agentwalletrpc.ReserveUtxosRequest\x1a$.agentwalletrpc.ReserveUtxosResponse\x12k\n" +
	"\x12ReleaseReservation\x12).agentwalletrpc.ReleaseReservationRequest\x1a*.agentwalletrpc.ReleaseReservationResponse\x12Y\n" +
	"\fGetOperation\x12#.agentwalletrpc.GetOperationRequest\x1a$.agentwalletrpc.GetOperationResponseBAZ?github.com/btcsuite/btcwallet/rpc/agentwalletrpc;agentwalletrpcb\x06proto3"

var (
	file_agentwallet_proto_rawDescOnce sync.Once
	file_agentwallet_proto_rawDescData []byte
)

func file_agentwallet_proto_rawDescGZIP() []byte {
	file_agentwallet_proto_rawDescOnce.Do(func() {
		file_agentwallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentwallet_proto_rawDesc), len(file_agentwallet_proto_rawDesc)))
	})
	return file_agentwallet_proto_rawDescData
}

var file_agentwallet_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_agentwallet_proto_goTypes = []any{
	(*RequestMeta)(nil),                // 0: agentwalletrpc.RequestMeta
	(*ResponseMeta)(nil),               // 1: agentwalletrpc.ResponseMeta
	(*WalletState)(nil),                // 2: agentwalletrpc.WalletState
	(*GetWalletStateRequest)(nil),      // 3: agentwalletrpc.GetWalletStateRequest
	(*GetWalletStateResponse)(nil),     // 4: agentwalletrpc.GetWalletStateResponse
	(*Utxo)(nil),                       // 5: agentwalletrpc.Utxo
	(*ListUtxosRequest)(nil),           // 6: agentwalletrpc.ListUtxosRequest
	(*ListUtxosResponse)(nil),          // 7: agentwalletrpc.ListUtxosResponse
	(*ExpiryPolicy)(nil),               // 8: agentwalletrpc.ExpiryPolicy
	(*ExpiryRisk)(nil),                 // 9: agentwalletrpc.ExpiryRisk
	(*GetExpiryRiskRequest)(nil),       // 10: agentwalletrpc.GetExpiryRiskRequest
	(*GetExpiryRiskResponse)(nil),      // 11: agentwalletrpc.GetExpiryRiskResponse
	(*TransactionSummary)(nil),         // 12: agentwalletrpc.TransactionSummary
	(*Operation)(nil),                  // 13: agentwalletrpc.Operation
	(*PreviewRenewalRequest)(nil),      // 14: agentwalletrpc.PreviewRenewalRequest
	(*PreviewRenewalResponse)(nil),     // 15: agentwalletrpc.PreviewRenewalResponse
	(*SubmitRenewalRequest)(nil),       // 16: agentwalletrpc.SubmitRenewalRequest
	(*SubmitRenewalResponse)(nil),      // 17: agentwalletrpc.SubmitRenewalResponse
	(*ReserveUtxosRequest)(nil),        // 18: agentwalletrpc.ReserveUtxosRequest
	(*ReserveUtxosResponse)(nil),       // 19: agentwalletrpc.ReserveUtxosResponse
	(*ReleaseReservationRequest)(nil),  // 20: agentwalletrpc.ReleaseReservationRequest
	(*ReleaseReservationResponse)(nil), // 21: agentwalletrpc.ReleaseReservationResponse
	(*GetOperationRequest)(nil),        // 22: agentwalletrpc.GetOperationRequest
	(*GetOperationResponse)(nil),       // 23: agentwalletrpc.GetOperationResponse
}
var file_agentwallet_proto_depIdxs = []int32{
	0,  // 0: agentwalletrpc.GetWalletStateRequest.meta:type_name -> agentwalletrpc.RequestMeta
	1,  // 1: agentwalletrpc.GetWalletStateResponse.meta:type_name -> agentwalletrpc.ResponseMeta
	2,  // 2: agentwalletrpc.GetWalletStateResponse.state:type_name -> agentwalletrpc.WalletState
	0,  // 3: agentwalletrpc.ListUtxosRequest.meta:type_name -> agentwalletrpc.RequestMeta
	1,  // 4: agentwalletrpc.ListUtxosResponse.meta:type_name -> agentwalletrpc.ResponseMeta
	5,  // 5: agentwalletrpc.ListUtxosResponse.utxos:type_name -> agentwalletrpc.Utxo
	0,  // 6: agentwalletrpc.GetExpiryRiskRequest.meta:type_name -> agentwalletrpc.RequestMeta
	8,  // 7: agentwalletrpc.GetExpiryRiskRequest.policy:type_name -> agentwalletrpc.ExpiryPolicy
	1,  // 8: agentwalletrpc.GetExpiryRiskResponse.meta:type_name -> agentwalletrpc.ResponseMeta
	8,  // 9: agentwalletrpc.GetExpiryRiskResponse.effective_policy:type_name -> agentwalletrpc.ExpiryPolicy
	9,  // 10: agentwalletrpc.GetExpiryRiskResponse.items:type_name -> agentwalletrpc.ExpiryRisk
	12, // 11: agentwalletrpc.Operation.summary:type_name -> agentwalletrpc.TransactionSummary
	9,  // 12: agentwalletrpc.Operation.expiry_risks:type_name -> agentwalletrpc.ExpiryRisk
	8,  // 13: agentwalletrpc.Operation.effective_policy:type_name -> agentwalletrpc.ExpiryPolicy
	0,  // 14: agentwalletrpc.PreviewRenewalRequest.meta:type_name -> agentwalletrpc.RequestMeta
	8,  // 15: agentwalletrpc.PreviewRenewalRequest.expiry_policy:type_name -> agentwalletrpc.ExpiryPolicy
	1,  // 16: agentwalletrpc.PreviewRenewalResponse.meta:type_name -> agentwalletrpc.ResponseMeta
	13, // 17: agentwalletrpc.PreviewRenewalResponse.operation:type_name -> agentwalletrpc.Operation
	12, // 18: agentwalletrpc.PreviewRenewalResponse.summary:type_name -> agentwalletrpc.TransactionSummary
	8,  // 19: agentwalletrpc.PreviewRenewalResponse.effective_policy:type_name -> agentwalletrpc.ExpiryPolicy
	9,  // 20: agentwalletrpc.PreviewRenewalResponse.expiry_risks:type_name -> agentwalletrpc.ExpiryRisk
	0,  // 21: agentwalletrpc.SubmitRenewalRequest.meta:type_name -> agentwalletrpc.RequestMeta
	1,  // 22: agentwalletrpc.SubmitRenewalResponse.meta:type_name -> agentwalletrpc.ResponseMeta
	13, // 23: agentwalletrpc.SubmitRenewalResponse.operation:type_name -> agentwalletrpc.Operation
	12, // 24: agentwalletrpc.SubmitRenewalResponse.summary:type_name -> agentwalletrpc.TransactionSummary
	8,  // 25: agentwalletrpc.SubmitRenewalResponse.effective_policy:type_name -> agentwalletrpc.ExpiryPolicy
	9,  // 26: agentwalletrpc.SubmitRenewalResponse.expiry_risks:type_name -> agentwalletrpc.ExpiryRisk
	0,  // 27: agentwalletrpc.ReserveUtxosRequest.meta:type_name -> agentwalletrpc.RequestMeta
	1,  // 28: agentwalletrpc.ReserveUtxosResponse.meta:type_name -> agentwalletrpc.ResponseMeta
	0,  // 29: agentwalletrpc.ReleaseReservationRequest.meta:type_name -> agentwalletrpc.RequestMeta
	1,  // 30: agentwalletrpc.ReleaseReservationResponse.meta:type_name -> agentwalletrpc.ResponseMeta
	0,  // 31: agentwalletrpc.GetOperationRequest.meta:type_name -> agentwalletrpc.RequestMeta
	1,  // 32: agentwalletrpc.GetOperationResponse.meta:type_name -> agentwalletrpc.ResponseMeta
	13, // 33: agentwalletrpc.GetOperationResponse.operation:type_name -> agentwalletrpc.Operation
	3,  // 34: agentwalletrpc.AgentWalletService.GetWalletState:input_type -> agentwalletrpc.GetWalletStateRequest
	6,  // 35: agentwalletrpc.AgentWalletService.ListUtxos:input_type -> agentwalletrpc.ListUtxosRequest
	10, // 36: agentwalletrpc.AgentWalletService.GetExpiryRisk:input_type -> agentwalletrpc.GetExpiryRiskRequest
	14, // 37: agentwalletrpc.AgentWalletService.PreviewRenewal:input_type -> agentwalletrpc.PreviewRenewalRequest
	16, // 38: agentwalletrpc.AgentWalletService.SubmitRenewal:input_type -> agentwalletrpc.SubmitRenewalRequest
	18, // 39: agentwalletrpc.AgentWalletService.ReserveUtxos:input_type -> agentwalletrpc.ReserveUtxosRequest
	20, // 40: agentwalletrpc.AgentWalletService.ReleaseReservation:input_type -> agentwalletrpc.ReleaseReservationRequest
	22, // 41: agentwalletrpc.AgentWalletService.GetOperation:input_type -> agentwalletrpc.GetOperationRequest
	4,  // 42: agentwalletrpc.AgentWalletService.GetWalletState:output_type -> agentwalletrpc.GetWalletStateResponse
	7,  // 43: agentwalletrpc.AgentWalletService.ListUtxos:output_type -> agentwalletrpc.ListUtxosResponse
	11, // 44: agentwalletrpc.AgentWalletService.GetExpiryRisk:output_type -> agentwalletrpc.GetExpiryRiskResponse
	15, // 45: agentwalletrpc.AgentWalletService.PreviewRenewal:output_type -> agentwalletrpc.PreviewRenewalResponse
	17, // 46: agentwalletrpc.AgentWalletService.SubmitRenewal:output_type -> agentwalletrpc.SubmitRenewalResponse
	19, // 47: agentwalletrpc.AgentWalletService.ReserveUtxos:output_type -> agentwalletrpc.ReserveUtxosResponse
	21, // 48: agentwalletrpc.AgentWalletService.ReleaseReservation:output_type -> agentwalletrpc.ReleaseReservationResponse
	23, // 49: agentwalletrpc.AgentWalletService.GetOperation:output_type -> agentwalletrpc.GetOperationResponse
	42, // [42:50] is the sub-list for method output_type
	34, // [34:42] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_agentwallet_proto_init() }
func file_agentwallet_proto_init() {
	if File_agentwallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentwallet_proto_rawDesc), len(file_agentwallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agentwallet_proto_goTypes,
		DependencyIndexes: file_agentwallet_proto_depIdxs,
		MessageInfos:      file_agentwallet_proto_msgTypes,
	}.Build()
	File_agentwallet_proto = out.File
	file_agentwallet_proto_goTypes = nil
	file_agentwallet_proto_depIdxs = nil
}
