// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: agentwallet.proto

package agentwalletrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentWalletService_GetWalletState_FullMethodName     = "/agentwalletrpc.AgentWalletService/GetWalletState"
	AgentWalletService_ListUtxos_FullMethodName          = "/agentwalletrpc.AgentWalletService/ListUtxos"
	AgentWalletService_GetExpiryRisk_FullMethodName      = "/agentwalletrpc.AgentWalletService/GetExpiryRisk"
	AgentWalletService_PreviewRenewal_FullMethodName     = "/agentwalletrpc.AgentWalletService/PreviewRenewal"
	AgentWalletService_SubmitRenewal_FullMethodName      = "/agentwalletrpc.AgentWalletService/SubmitRenewal"
	AgentWalletService_ReserveUtxos_FullMethodName       = "/agentwalletrpc.AgentWalletService/ReserveUtxos"
	AgentWalletService_ReleaseReservation_FullMethodName = "/agentwalletrpc.AgentWalletService/ReleaseReservation"
	AgentWalletService_GetOperation_FullMethodName       = "/agentwalletrpc.AgentWalletService/GetOperation"
)

// AgentWalletServiceClient is the client API for AgentWalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentWalletService defines a phase-1 programmatic API for AI agents and
// human-facing CLI adapters. The initial scope covers wallet state, UTXO
// inspection, expiry risk analysis, renewal planning/submission, persistent
// reservations, and operation lookup.
type AgentWalletServiceClient interface {
	GetWalletState(ctx context.Context, in *GetWalletStateRequest, opts ...grpc.CallOption) (*GetWalletStateResponse, error)
	ListUtxos(ctx context.Context, in *ListUtxosRequest, opts ...grpc.CallOption) (*ListUtxosResponse, error)
	GetExpiryRisk(ctx context.Context, in *GetExpiryRiskRequest, opts ...grpc.CallOption) (*GetExpiryRiskResponse, error)
	PreviewRenewal(ctx context.Context, in *PreviewRenewalRequest, opts ...grpc.CallOption) (*PreviewRenewalResponse, error)
	SubmitRenewal(ctx context.Context, in *SubmitRenewalRequest, opts ...grpc.CallOption) (*SubmitRenewalResponse, error)
	ReserveUtxos(ctx context.Context, in *ReserveUtxosRequest, opts ...grpc.CallOption) (*ReserveUtxosResponse, error)
	ReleaseReservation(ctx context.Context, in *ReleaseReservationRequest, opts ...grpc.CallOption) (*ReleaseReservationResponse, error)
	GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*GetOperationResponse, error)
}

type agentWalletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentWalletServiceClient(cc grpc.ClientConnInterface) AgentWalletServiceClient {
	return &agentWalletServiceClient{cc}
}

func (c *agentWalletServiceClient) GetWalletState(ctx context.Context, in *GetWalletStateRequest, opts ...grpc.CallOption) (*GetWalletStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletStateResponse)
	err := c.cc.Invoke(ctx, AgentWalletService_GetWalletState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentWalletServiceClient) ListUtxos(ctx context.Context, in *ListUtxosRequest, opts ...grpc.CallOption) (*ListUtxosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUtxosResponse)
	err := c.cc.Invoke(ctx, AgentWalletService_ListUtxos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentWalletServiceClient) GetExpiryRisk(ctx context.Context, in *GetExpiryRiskRequest, opts ...grpc.CallOption) (*GetExpiryRiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExpiryRiskResponse)
	err := c.cc.Invoke(ctx, AgentWalletService_GetExpiryRisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentWalletServiceClient) PreviewRenewal(ctx context.Context, in *PreviewRenewalRequest, opts ...grpc.CallOption) (*PreviewRenewalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewRenewalResponse)
	err := c.cc.Invoke(ctx, AgentWalletService_PreviewRenewal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentWalletServiceClient) SubmitRenewal(ctx context.Context, in *SubmitRenewalRequest, opts ...grpc.CallOption) (*SubmitRenewalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitRenewalResponse)
	err := c.cc.Invoke(ctx, AgentWalletService_SubmitRenewal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentWalletServiceClient) ReserveUtxos(ctx context.Context, in *ReserveUtxosRequest, opts ...grpc.CallOption) (*ReserveUtxosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveUtxosResponse)
	err := c.cc.Invoke(ctx, AgentWalletService_ReserveUtxos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentWalletServiceClient) ReleaseReservation(ctx context.Context, in *ReleaseReservationRequest, opts ...grpc.CallOption) (*ReleaseReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseReservationResponse)
	err := c.cc.Invoke(ctx, AgentWalletService_ReleaseReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentWalletServiceClient) GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*GetOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOperationResponse)
	err := c.cc.Invoke(ctx, AgentWalletService_GetOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentWalletServiceServer is the server API for AgentWalletService service.
// All implementations must embed UnimplementedAgentWalletServiceServer
// for forward compatibility.
//
// AgentWalletService defines a phase-1 programmatic API for AI agents and
// human-facing CLI adapters. The initial scope covers wallet state, UTXO
// inspection, expiry risk analysis, renewal planning/submission, persistent
// reservations, and operation lookup.
type AgentWalletServiceServer interface {
	GetWalletState(context.Context, *GetWalletStateRequest) (*GetWalletStateResponse, error)
	ListUtxos(context.Context, *ListUtxosRequest) (*ListUtxosResponse, error)
	GetExpiryRisk(context.Context, *GetExpiryRiskRequest) (*GetExpiryRiskResponse, error)
	PreviewRenewal(context.Context, *PreviewRenewalRequest) (*PreviewRenewalResponse, error)
	SubmitRenewal(context.Context, *SubmitRenewalRequest) (*SubmitRenewalResponse, error)
	ReserveUtxos(context.Context, *ReserveUtxosRequest) (*ReserveUtxosResponse, error)
	ReleaseReservation(context.Context, *ReleaseReservationRequest) (*ReleaseReservationResponse, error)
	GetOperation(context.Context, *GetOperationRequest) (*GetOperationResponse, error)
	mustEmbedUnimplementedAgentWalletServiceServer()
}

// UnimplementedAgentWalletServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentWalletServiceServer struct{}

func (UnimplementedAgentWalletServiceServer) GetWalletState(context.Context, *GetWalletStateRequest) (*GetWalletStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletState not implemented")
}
func (UnimplementedAgentWalletServiceServer) ListUtxos(context.Context, *ListUtxosRequest) (*ListUtxosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUtxos not implemented")
}
func (UnimplementedAgentWalletServiceServer) GetExpiryRisk(context.Context, *GetExpiryRiskRequest) (*GetExpiryRiskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExpiryRisk not implemented")
}
func (UnimplementedAgentWalletServiceServer) PreviewRenewal(context.Context, *PreviewRenewalRequest) (*PreviewRenewalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreviewRenewal not implemented")
}
func (UnimplementedAgentWalletServiceServer) SubmitRenewal(context.Context, *SubmitRenewalRequest) (*SubmitRenewalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitRenewal not implemented")
}
func (UnimplementedAgentWalletServiceServer) ReserveUtxos(context.Context, *ReserveUtxosRequest) (*ReserveUtxosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReserveUtxos not implemented")
}
func (UnimplementedAgentWalletServiceServer) ReleaseReservation(context.Context, *ReleaseReservationRequest) (*ReleaseReservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseReservation not implemented")
}
func (UnimplementedAgentWalletServiceServer) GetOperation(context.Context, *GetOperationRequest) (*GetOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOperation not implemented")
}
func (UnimplementedAgentWalletServiceServer) mustEmbedUnimplementedAgentWalletServiceServer() {}
func (UnimplementedAgentWalletServiceServer) testEmbeddedByValue()                            {}

// UnsafeAgentWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentWalletServiceServer will
// result in compilation errors.
type UnsafeAgentWalletServiceServer interface {
	mustEmbedUnimplementedAgentWalletServiceServer()
}

func RegisterAgentWalletServiceServer(s grpc.ServiceRegistrar, srv AgentWalletServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentWalletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentWalletService_ServiceDesc, srv)
}

func _AgentWalletService_GetWalletState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWalletServiceServer).GetWalletState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWalletService_GetWalletState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWalletServiceServer).GetWalletState(ctx, req.(*GetWalletStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentWalletService_ListUtxos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUtxosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWalletServiceServer).ListUtxos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWalletService_ListUtxos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWalletServiceServer).ListUtxos(ctx, req.(*ListUtxosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentWalletService_GetExpiryRisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExpiryRiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWalletServiceServer).GetExpiryRisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWalletService_GetExpiryRisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWalletServiceServer).GetExpiryRisk(ctx, req.(*GetExpiryRiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentWalletService_PreviewRenewal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewRenewalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWalletServiceServer).PreviewRenewal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWalletService_PreviewRenewal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWalletServiceServer).PreviewRenewal(ctx, req.(*PreviewRenewalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentWalletService_SubmitRenewal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRenewalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWalletServiceServer).SubmitRenewal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWalletService_SubmitRenewal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWalletServiceServer).SubmitRenewal(ctx, req.(*SubmitRenewalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentWalletService_ReserveUtxos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveUtxosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWalletServiceServer).ReserveUtxos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWalletService_ReserveUtxos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWalletServiceServer).ReserveUtxos(ctx, req.(*ReserveUtxosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentWalletService_ReleaseReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWalletServiceServer).ReleaseReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWalletService_ReleaseReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWalletServiceServer).ReleaseReservation(ctx, req.(*ReleaseReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentWalletService_GetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWalletServiceServer).GetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWalletService_GetOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWalletServiceServer).GetOperation(ctx, req.(*GetOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentWalletService_ServiceDesc is the grpc.ServiceDesc for AgentWalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentWalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentwalletrpc.AgentWalletService",
	HandlerType: (*AgentWalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWalletState",
			Handler:    _AgentWalletService_GetWalletState_Handler,
		},
		{
			MethodName: "ListUtxos",
			Handler:    _AgentWalletService_ListUtxos_Handler,
		},
		{
			MethodName: "GetExpiryRisk",
			Handler:    _AgentWalletService_GetExpiryRisk_Handler,
		},
		{
			MethodName: "PreviewRenewal",
			Handler:    _AgentWalletService_PreviewRenewal_Handler,
		},
		{
			MethodName: "SubmitRenewal",
			Handler:    _AgentWalletService_SubmitRenewal_Handler,
		},
		{
			MethodName: "ReserveUtxos",
			Handler:    _AgentWalletService_ReserveUtxos_Handler,
		},
		{
			MethodName: "ReleaseReservation",
			Handler:    _AgentWalletService_ReleaseReservation_Handler,
		},
		{
			MethodName: "GetOperation",
			Handler:    _AgentWalletService_GetOperation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agentwallet.proto",
}
