// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.4
// source: remotesigner.proto

package remotesignerrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Auth          []byte                 `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionRequest) Reset() {
	*x = OpenSessionRequest{}
	mi := &file_remotesigner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionRequest) ProtoMessage() {}

func (x *OpenSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remotesigner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionRequest.ProtoReflect.Descriptor instead.
func (*OpenSessionRequest) Descriptor() ([]byte, []int) {
	return file_remotesigner_proto_rawDescGZIP(), []int{0}
}

func (x *OpenSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OpenSessionRequest) GetAuth() []byte {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *OpenSessionRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *OpenSessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type OpenSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiresAtUnix int64                  `protobuf:"varint,1,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionResponse) Reset() {
	*x = OpenSessionResponse{}
	mi := &file_remotesigner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionResponse) ProtoMessage() {}

func (x *OpenSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remotesigner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionResponse.ProtoReflect.Descriptor instead.
func (*OpenSessionResponse) Descriptor() ([]byte, []int) {
	return file_remotesigner_proto_rawDescGZIP(), []int{1}
}

func (x *OpenSessionResponse) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_remotesigner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remotesigner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_remotesigner_proto_rawDescGZIP(), []int{2}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CloseSessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_remotesigner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remotesigner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_remotesigner_proto_rawDescGZIP(), []int{3}
}

type FinalizePsbtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AccountNumber uint32                 `protobuf:"varint,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	UnsignedPsbt  []byte                 `protobuf:"bytes,3,opt,name=unsigned_psbt,json=unsignedPsbt,proto3" json:"unsigned_psbt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizePsbtRequest) Reset() {
	*x = FinalizePsbtRequest{}
	mi := &file_remotesigner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizePsbtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizePsbtRequest) ProtoMessage() {}

func (x *FinalizePsbtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remotesigner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizePsbtRequest.ProtoReflect.Descriptor instead.
func (*FinalizePsbtRequest) Descriptor() ([]byte, []int) {
	return file_remotesigner_proto_rawDescGZIP(), []int{4}
}

func (x *FinalizePsbtRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *FinalizePsbtRequest) GetAccountNumber() uint32 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *FinalizePsbtRequest) GetUnsignedPsbt() []byte {
	if x != nil {
		return x.UnsignedPsbt
	}
	return nil
}

type FinalizePsbtResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignedPsbt    []byte                 `protobuf:"bytes,1,opt,name=signed_psbt,json=signedPsbt,proto3" json:"signed_psbt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizePsbtResponse) Reset() {
	*x = FinalizePsbtResponse{}
	mi := &file_remotesigner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizePsbtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizePsbtResponse) ProtoMessage() {}

func (x *FinalizePsbtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remotesigner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizePsbtResponse.ProtoReflect.Descriptor instead.
func (*FinalizePsbtResponse) Descriptor() ([]byte, []int) {
	return file_remotesigner_proto_rawDescGZIP(), []int{5}
}

func (x *FinalizePsbtResponse) GetSignedPsbt() []byte {
	if x != nil {
		return x.SignedPsbt
	}
	return nil
}

var File_remotesigner_proto protoreflect.FileDescriptor

const file_remotesigner_proto_rawDesc = "" +
	"\n" +
	"\x12remotesigner.proto\x12\x0fremotesignerrpc\"\x80\x01\n" +
	"\x12OpenSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04auth\x18\x02 \x01(\fR\x04auth\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"=\n" +
	"\x13OpenSessionResponse\x12&\n" +
	"\x0fexpires_at_unix\x18\x01 \x01(\x03R\rexpiresAtUnix\"L\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x16\n" +
	"\x14CloseSessionResponse\"\x80\x01\n" +
	"\x13FinalizePsbtRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\rR\raccountNumber\x12#\n" +
	"\runsigned_psbt\x18\x03 \x01(\fR\funsignedPsbt\"7\n" +
	"\x14FinalizePsbtResponse\x12\x1f\n" +
	"\vsigned_psbt\x18\x01 \x01(\fR\n" +
	"signedPsbt2\xa9\x02\n" +
	"\x13RemoteSignerService\x12X\n" +
	"\vOpenSession\x12#.remotesignerrpc.OpenSessionRequest\x1a$.remotesignerrpc.OpenSessionResponse\x12[\n" +
	"\fCloseSession\x12$.remotesignerrpc.CloseSessionRequest\x1a%.remotesignerrpc.CloseSessionResponse\x12[\n" +
	"\fFinalizePsbt\x12$.remotesignerrpc.FinalizePsbtRequest\x1a%.remotesignerrpc.FinalizePsbtResponseBCZAgithub.com/btcsuite/btcwallet/rpc/remotesignerrpc;remotesignerrpcb\x06proto3"

var (
	file_remotesigner_proto_rawDescOnce sync.Once
	file_remotesigner_proto_rawDescData []byte
)

func file_remotesigner_proto_rawDescGZIP() []byte {
	file_remotesigner_proto_rawDescOnce.Do(func() {
		file_remotesigner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remotesigner_proto_rawDesc), len(file_remotesigner_proto_rawDesc)))
	})
	return file_remotesigner_proto_rawDescData
}

var file_remotesigner_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_remotesigner_proto_goTypes = []any{
	(*OpenSessionRequest)(nil),   // 0: remotesignerrpc.OpenSessionRequest
	(*OpenSessionResponse)(nil),  // 1: remotesignerrpc.OpenSessionResponse
	(*CloseSessionRequest)(nil),  // 2: remotesignerrpc.CloseSessionRequest
	(*CloseSessionResponse)(nil), // 3: remotesignerrpc.CloseSessionResponse
	(*FinalizePsbtRequest)(nil),  // 4: remotesignerrpc.FinalizePsbtRequest
	(*FinalizePsbtResponse)(nil), // 5: remotesignerrpc.FinalizePsbtResponse
}
var file_remotesigner_proto_depIdxs = []int32{
	0, // 0: remotesignerrpc.RemoteSignerService.OpenSession:input_type -> remotesignerrpc.OpenSessionRequest
	2, // 1: remotesignerrpc.RemoteSignerService.CloseSession:input_type -> remotesignerrpc.CloseSessionRequest
	4, // 2: remotesignerrpc.RemoteSignerService.FinalizePsbt:input_type -> remotesignerrpc.FinalizePsbtRequest
	1, // 3: remotesignerrpc.RemoteSignerService.OpenSession:output_type -> remotesignerrpc.OpenSessionResponse
	3, // 4: remotesignerrpc.RemoteSignerService.CloseSession:output_type -> remotesignerrpc.CloseSessionResponse
	5, // 5: remotesignerrpc.RemoteSignerService.FinalizePsbt:output_type -> remotesignerrpc.FinalizePsbtResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_remotesigner_proto_init() }
func file_remotesigner_proto_init() {
	if File_remotesigner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remotesigner_proto_rawDesc), len(file_remotesigner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remotesigner_proto_goTypes,
		DependencyIndexes: file_remotesigner_proto_depIdxs,
		MessageInfos:      file_remotesigner_proto_msgTypes,
	}.Build()
	File_remotesigner_proto = out.File
	file_remotesigner_proto_goTypes = nil
	file_remotesigner_proto_depIdxs = nil
}
